[package]
name = "tmx2rms"
version = "0.1.0"
authors = ["Michael Hitchens <mdhitchens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmx = "^0.3.1"
